export enum Channel {
    WHATSAPP = "WHATSAPP",
    SMS = "SMS",
    EMAIL = "EMAIL",
    GOOGLE_CHAT = "GOOGLE_CHAT",    
}

export enum MessageModel {
    ALERT_NOTIFICATION = "ALERT_NOTIFICATION",
    MOVEMENT_ALERT = "MOVEMENT_ALERT",
    QUALITY_ALERT = "QUALITY_ALERT",    
    WARNING_POE_ALERT = "WARNING_POE_ALERT",
    CRITICAL_POE_ALERT = "CRITICAL_POE_ALERT",
    MEDIUM_RISK_ALERT =  "MEDIUM_RISK_ALERT",
    POE_EXPIRES_ALERT = "POE_EXPIRES_ALERT",
    NOT_VISIBLE_ALERT = "NOT_VISIBLE_ALERT",
}

export enum Language {
    ES = "ES",
    PT = "PT",
}